#include "HaGdi.h"

const wxColour HaGdi::COMMENT_BACK_COLOR(0xDD, 0xEE, 0xFF);
const wxColour HaGdi::DEFICIT_COLOR(255, 0, 0);
const wxColour HaGdi::SURPLUS_COLOR(0, 255, 0);

const wxFont HaGdi::DIGI_FONT(16, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL);
const wxFont HaGdi::BIG_FONT(18, wxFONTFAMILY_SCRIPT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL);
const wxFont HaGdi::BIG_MONO_FONT(18, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL);
